import fs from "fs";
import path from "path";
import { db } from "../db.js";

/**
 * V2 Synthetic Cloud Reality Engine Data Loader
 * Reads the 4 CSV files generated by cloud_simulator_v2.py
 * and bulk-inserts them into the SQLite database.
 */

const V2_DIR = path.resolve(process.cwd(), "Synthetic Engine (v2.0)");

export function isV2DataAvailable(): boolean {
    return fs.existsSync(path.join(V2_DIR, "resource_inventory.csv"));
}

export function loadV2Data() {
    if (!isV2DataAvailable()) {
        console.log("[V2 Loader] No V2 synthetic data found, skipping.");
        return;
    }

    console.log("[V2 Loader] Loading Synthetic Cloud Reality Engine v2.0 data...");

    const existing = db.prepare("SELECT COUNT(*) as c FROM resources").get() as { c: number };
    if (existing.c > 20) {
        console.log("[V2 Loader] Data already loaded, skipping.");
        return;
    }

    loadInventory();
    loadMetrics();
    loadBilling();
    loadAPILogs();

    console.log("[V2 Loader] All V2 datasets loaded successfully.");
}

function parseCSV(filePath: string): Record<string, string>[] {
    const content = fs.readFileSync(filePath, "utf-8");
    const lines = content.split("\n").filter(l => l.trim().length > 0);
    if (lines.length < 2) return [];

    const headers = lines[0].split(",").map(h => h.trim());
    const rows: Record<string, string>[] = [];

    for (let i = 1; i < lines.length; i++) {
        const values = lines[i].split(",");
        const row: Record<string, string> = {};
        for (let j = 0; j < headers.length; j++) {
            row[headers[j]] = (values[j] || "").trim();
        }
        rows.push(row);
    }
    return rows;
}

function loadInventory() {
    const rows = parseCSV(path.join(V2_DIR, "resource_inventory.csv"));
    console.log(`  [Inventory] Loading ${rows.length} resources...`);

    const insert = db.prepare(`
    INSERT OR IGNORE INTO resources (id, provider, service, name, region, status, instance_type, owner_tag, cost_per_hour)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

    db.transaction(() => {
        for (const r of rows) {
            // Extract a readable name from the resource_id
            const name = r.resource_id.includes("/")
                ? r.resource_id.split("/").pop() || r.resource_id
                : r.resource_id;

            insert.run(
                r.resource_id,
                r.provider,
                r.resource_type,
                name,
                r.region,
                r.status || "running",
                r.instance_type,
                r.owner_tag || "Unknown",
                parseFloat(r.cost_per_hour) || 0
            );
        }
    })();
    console.log(`  [Inventory] ✓ ${rows.length} resources loaded`);
}

function loadMetrics() {
    const rows = parseCSV(path.join(V2_DIR, "resource_metrics.csv"));
    console.log(`  [Metrics] Loading ${rows.length} metric rows...`);

    const insert = db.prepare(`
    INSERT INTO metrics (resource_id, cpu_utilization, gpu_utilization, memory_usage, disk_io, network_in, network_out, cost_per_hour, timestamp)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

    // Sample every Nth row to keep DB manageable for demo
    const sampleRate = rows.length > 50000 ? Math.ceil(rows.length / 50000) : 1;
    let loaded = 0;

    db.transaction(() => {
        for (let i = 0; i < rows.length; i += sampleRate) {
            const m = rows[i];
            const cpu = parseFloat(m.cpu_usage);
            if (isNaN(cpu) || m.timestamp.length < 10) continue; // skip dirty data

            insert.run(
                m.resource_id,
                cpu,
                parseFloat(m.gpu_usage) || 0,
                parseFloat(m.memory_usage) || 0,
                parseFloat(m.disk_io) || 0,
                parseFloat(m.network_in) || 0,
                parseFloat(m.network_out) || 0,
                0, // cost_per_hour comes from billing table
                m.timestamp
            );
            loaded++;
        }
    })();
    console.log(`  [Metrics] ✓ ${loaded} metric rows loaded (sampled ${sampleRate}:1 from ${rows.length})`);
}

function loadBilling() {
    const rows = parseCSV(path.join(V2_DIR, "billing_data.csv"));
    console.log(`  [Billing] Loading ${rows.length} billing rows...`);

    const insert = db.prepare(`
    INSERT INTO billing (resource_id, service, cost_per_hour, total_cost, data_transfer_gb, storage_gb, timestamp)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `);

    const sampleRate = rows.length > 50000 ? Math.ceil(rows.length / 50000) : 1;
    let loaded = 0;

    db.transaction(() => {
        for (let i = 0; i < rows.length; i += sampleRate) {
            const b = rows[i];
            const cost = parseFloat(b.cost_per_hour);
            if (isNaN(cost) || b.timestamp === "invalid-date") continue; // skip dirty

            insert.run(
                b.resource_id,
                b.service,
                cost,
                parseFloat(b.total_cost) || 0,
                parseFloat(b.data_transfer_gb) || 0,
                parseFloat(b.storage_gb) || 0,
                b.timestamp
            );
            loaded++;
        }
    })();
    console.log(`  [Billing] ✓ ${loaded} billing rows loaded (sampled ${sampleRate}:1 from ${rows.length})`);
}

function loadAPILogs() {
    const rows = parseCSV(path.join(V2_DIR, "api_activity_logs.csv"));
    console.log(`  [API Logs] Loading ${rows.length} API activity rows...`);

    const insert = db.prepare(`
    INSERT INTO api_logs (user_id, action, resource_id, region, status, error_code, source_ip, timestamp)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);

    // API logs can be huge — sample to ~30K rows
    const sampleRate = rows.length > 30000 ? Math.ceil(rows.length / 30000) : 1;
    let loaded = 0;

    db.transaction(() => {
        for (let i = 0; i < rows.length; i += sampleRate) {
            const l = rows[i];
            insert.run(
                l.user_id, l.action, l.resource_id, l.region,
                l.status, l.error_code, l.source_ip, l.timestamp
            );
            loaded++;
        }
    })();
    console.log(`  [API Logs] ✓ ${loaded} API log rows loaded (sampled ${sampleRate}:1 from ${rows.length})`);
}
